[project]
name = "subsurfacedoc-iq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "databricks-sdk>=0.123.0",
    "dlt[duckdb]>=1.29.1",
    "gitsource>=0.0.5",
    "google-genai>=2.14.0",
    "minsearch>=0.2.0",
    "numpy>=2.5.1",
    "onnxruntime>=1.28.0",
    "openai>=2.50.0",
    "opentelemetry-api>=1.44.0",
    "opentelemetry-sdk>=1.44.0",
    "pandas>=3.0.5",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.4",
    "pydantic-ai>=2.31.1",
    "pymupdf>=1.28.0",
    "pypdf>=6.14.2",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "sentence-transformers>=5.6.1",
    "sqlalchemy>=2.0.51",
    "sqlitesearch>=0.3.0",
    "streamlit>=1.60.0",
    "tokenizers>=0.22.2",
    "tqdm>=4.70.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "pytest>=9.1.1",
]
